---
- name: Create {{ composer_working_dir }}/ directory
  file:
    path: "{{ composer_working_dir }}"
    state: directory
  become: yes

- name: Install drush - {{ drush_location }}
  command: "composer require drush/drush --working-dir {{ composer_working_dir }}"
  become: yes

- name: Create symlink to the latest drush
  file:
    src: "{{ composer_working_dir }}/vendor/bin/drush"
    path: "{{ drush_location }}"
    state: link
  become: yes
