---
- name: Create {{ composer_working_dir }}/ directory
  file: path={{ composer_working_dir }} state=directory
  become: True

- name: Install drush - {{ drush_location }}
  command: "composer require drush/drush:8.* --working-dir {{ composer_working_dir }}"
  become: True

- name: Patch drush for minor version support
  patch:
    src: sop-587-drupal-versions-4038.patch
    basedir: "{{ composer_working_dir }}/vendor/drush/drush"
    strip: 1

- name: Create symlink to the latest drush
  file:
    src: "{{ composer_working_dir }}/vendor/bin/drush"
    path: "{{  drush_location }}"
    state: link
  become: True

- name: Clear drush cache
  command: "drush cc drush" 
